### ISSUE TITLE
Support for AGES 7.0?

### ISSUE THREAD

**Issue by zongiin** [makcimbx/tdahook#4]
is there support for AGES 7.0? I ported tdahook to 32bit so it works with Muv luv Steam version(which is 32 bit version of AGES 7.0), but I do not know how to find the pattern for translatetext and ui functions.

**Comment by makcimbx** [comment]
Since Ages 7.0 uses x32 architecture, it is not reasonable to add support for it specifically in this repository. Furthermore, Ages 7.0 requires text conversion from UTF16 to UTF8. And the functions themselves, which have to be hooked, are very different from TDA. About how to find the functions you need to use IDA Pro, although I also used Cheat Engine because it's faster when debugging, I recommend watching youtube videos related to reverse engineering. Look for UTF16 text in memory and put a breakpoint on it to find out the stacktrace, where as I remember you will need to find a function in IDA Pro that has 9 parameters or so, it will be a text translation function. Also I can tell you that for Muv-Luv and Muv-Luv Alternative the byte sequence will be different, and one byte will be different in memory from how it is written in the exe and seen in IDA Pro, so this should be considered when building the pattern.
